version: "3.8"

services:
    commenting_system:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: commenting_system
        ports:
            - "3000:3000" # Expose to host for nginx
        environment:
            - PORT=3000
            - NODE_ENV=production
        volumes:
            - ./public:/app/public
        restart: unless-stopped
